version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    ports:
      - 5555:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
